Add tools-pipelines to helm charts
geonetwork/geonetwork-helm-charts pull request #8
Opened 2024-02-13 16:35 UTC by f-necas

Creates a Job which wait for index in ES and then adds the pipeline.

2024-02-14 11:04 UTC, edevosc2c requested changes

2024-02-14 11:04 UTC, edevosc2c commented on gn-tools-pipeline/values.yaml
> +affinity: {}
You do not have any logic in the gntoolspipelines-job.yaml for handling this? Why keeping it?

2024-02-14 12:48 UTC, f-necas commented on gn-tools-pipeline/values.yaml
> +affinity: {}
Indeed. As they were keeped in other values files. I thought it was a good idea to keep it like that.

2024-02-14 12:56 UTC, edevosc2c requested changes

2024-02-14 12:56 UTC, edevosc2c commented on gn-tools-pipeline/templates/gntoolspipelines-job.yaml
> +          image: "{{ .Values.image }}"
That's incorrect, please take a look at how it is done in datahub: https://github.com/geonetwork/geonetwork-helm-charts/blob/main/datahub/templates/datahub-deployment.yaml#L36

2024-02-14 12:56 UTC, edevosc2c commented on gn-tools-pipeline/values.yaml
> +    memory: 128Mi
Still options not being used in the job manifest.

2024-02-14 12:56 UTC, edevosc2c commented on gn-tools-pipeline/values.yaml
> +  pullPolicy: Always
The logic for this option is missing.
https://github.com/geonetwork/geonetwork-helm-charts/blob/main/datahub/templates/datahub-deployment.yaml#L37

2024-02-14 12:57 UTC, edevosc2c requested changes

2024-02-14 12:57 UTC, edevosc2c commented on gn-tools-pipeline/templates/gntoolspipelines-job.yaml
> +      restartPolicy: Never
If you pass this option, then the job won't be retried in case of errors. Is this expected?

2024-02-16 14:39 UTC, edevosc2c approved these changes

2024-02-16 14:40 UTC, merged